"""schema initial

Revision ID: 86cc4ec86009
Revises: 
Create Date: 2026-09-01 15:33:55.230831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86cc4ec86009'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etablissement',
    sa.Column('etablissement_id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('ville', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('etablissement_id')
    )
    op.create_table('utilisateur',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('mot_de_passe_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('administrateur',
    sa.Column('utilisateur_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('utilisateur_id')
    )
    op.create_table('encadreur',
    sa.Column('utilisateur_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('utilisateur_id')
    )
    op.create_table('stagiaire',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('utilisateur_id', sa.UUID(), nullable=False),
    sa.Column('telephone', sa.String(length=30), nullable=True),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.Column('matricule', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricule'),
    sa.UniqueConstraint('utilisateur_id')
    )
    op.create_table('stage',
    sa.Column('stage_id', sa.UUID(), nullable=False),
    sa.Column('stagiaire_id', sa.UUID(), nullable=False),
    sa.Column('etablissement_id', sa.UUID(), nullable=True),
    sa.Column('encadreur_id', sa.UUID(), nullable=True),
    sa.Column('type_stage', sa.String(length=100), nullable=False),
    sa.Column('theme', sa.String(length=255), nullable=False),
    sa.Column('objectif_general', sa.Text(), nullable=True),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.Column('statut', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['encadreur_id'], ['utilisateur.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissement.etablissement_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stagiaire_id'], ['stagiaire.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('stage_id')
    )
    op.create_table('document_stage',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('stage_id', sa.UUID(), nullable=False),
    sa.Column('nom_doc', sa.String(length=255), nullable=False),
    sa.Column('type_doc', sa.String(length=100), nullable=False),
    sa.Column('chemin_fichier', sa.String(length=500), nullable=False),
    sa.Column('a_retourner', sa.Boolean(), nullable=False),
    sa.Column('statut_doc', sa.String(length=50), nullable=False),
    sa.Column('date_reception', sa.DateTime(), nullable=True),
    sa.Column('date_retour', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['stage_id'], ['stage.stage_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_table('evaluation',
    sa.Column('evaluation_id', sa.UUID(), nullable=False),
    sa.Column('stage_id', sa.UUID(), nullable=False),
    sa.Column('type_eval', sa.String(length=100), nullable=False),
    sa.Column('note_globale', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('appreciations', sa.Text(), nullable=True),
    sa.Column('statut', sa.String(length=50), nullable=False),
    sa.Column('date_evaluation', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stage_id'], ['stage.stage_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('evaluation_id')
    )
    op.create_table('permission',
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('stage_id', sa.UUID(), nullable=False),
    sa.Column('date_debut', sa.DateTime(), nullable=False),
    sa.Column('date_fin', sa.DateTime(), nullable=False),
    sa.Column('motif', sa.Text(), nullable=False),
    sa.Column('statut_perm', sa.String(length=50), nullable=False),
    sa.Column('commentaire_decision', sa.Text(), nullable=True),
    sa.Column('date_decision', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['stage_id'], ['stage.stage_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('permission_id')
    )
    op.create_table('tache',
    sa.Column('tache_id', sa.UUID(), nullable=False),
    sa.Column('stage_id', sa.UUID(), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_limite', sa.Date(), nullable=True),
    sa.Column('priorite', sa.String(length=50), nullable=False),
    sa.Column('statut_tache', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['stage_id'], ['stage.stage_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tache_id')
    )
    op.create_table('soumission',
    sa.Column('soumison_id', sa.UUID(), nullable=False),
    sa.Column('tache_id', sa.UUID(), nullable=False),
    sa.Column('num_version', sa.Integer(), nullable=False),
    sa.Column('contenu_lien', sa.String(length=500), nullable=True),
    sa.Column('commentaire_stagiaire', sa.Text(), nullable=True),
    sa.Column('date_soumission', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tache_id'], ['tache.tache_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('soumison_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('soumission')
    op.drop_table('tache')
    op.drop_table('permission')
    op.drop_table('evaluation')
    op.drop_table('document_stage')
    op.drop_table('stage')
    op.drop_table('stagiaire')
    op.drop_table('encadreur')
    op.drop_table('administrateur')
    op.drop_table('utilisateur')
    op.drop_table('etablissement')
    # ### end Alembic commands ###