"""add document taille_fichier

Revision ID: e86667a14da5
Revises: fa1ea1b815f5
Create Date: 2026-09-04 06:26:33.060321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e86667a14da5'
down_revision: Union[str, None] = 'fa1ea1b815f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_stage', sa.Column('taille_fichier', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_stage', 'taille_fichier')
    # ### end Alembic commands ###