"""add profile fields

Revision ID: fa1ea1b815f5
Revises: 86cc4ec86009
Create Date: 2026-09-04 06:10:45.909574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa1ea1b815f5'
down_revision: Union[str, None] = '86cc4ec86009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('encadreur', sa.Column('departement', sa.String(length=100), nullable=True))
    op.add_column('encadreur', sa.Column('specialite', sa.String(length=100), nullable=True))
    op.add_column('stagiaire', sa.Column('filiere', sa.String(length=100), nullable=True))
    op.add_column('stagiaire', sa.Column('periode_stage', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stagiaire', 'periode_stage')
    op.drop_column('stagiaire', 'filiere')
    op.drop_column('encadreur', 'specialite')
    op.drop_column('encadreur', 'departement')
    # ### end Alembic commands ###